---

- name: postmap transport_maps
  command: postmap /etc/postfix/transport_maps

- name: postmap virtual_alias_domains
  command: postmap /etc/postfix/virtual_alias_domains

- name: postmap virtual_alias_maps
  command: postmap /etc/postfix/virtual_alias_maps

- name: postmap virtual_mailbox_domains
  command: postmap /etc/postfix/virtual_mailbox_domains

- name: postmap virtual_mailbox_maps
  command: postmap /etc/postfix/virtual_mailbox_maps

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: reload postfix
  service:
    name: postfix
    state: reloaded
  listen:
    - new mailname
