---
# SPDX-FileCopyrightText: 2013 - 2022 Philipp Kaluza <consult@ghostroute.eu>
# SPDX-FileCopyrightText: 2016 - 2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

restic_server_backupstorage: "/srv/backupstorage/"

restic_server_flags: "--listen :8000"

# restic_server_allowoverwrites: true

restic_server_certificate_directory: /etc/ssl

restic_server_certificate_common_name: "{{ inventory_hostname }}"

# certificate_alt_names:
#   - "DNS:{{ restic_server_certificate_common_name }}"

# restic_server_certificate_name: "{{ restic_server_certificate_common_name | regex_replace(' ', '_') }}"
restic_server_certificate_name: "{{ restic_server_certificate_common_name | regex_replace(' ', '_') }}"
restic_server_certificate_file: "{{ restic_server_certificate_directory }}/certs/{{ restic_server_certificate_name }}.cert.pem"
restic_server_certificate_chain_file: "{{ restic_server_certificate_directory }}/certs/{{ restic_server_certificate_name }}.chain.pem"
restic_server_certificate_fullchain_file: "{{ restic_server_certificate_directory }}/certs/{{ restic_server_certificate_name }}.fullchain.pem"

restic_server_certificate_private_key_file: "{{ restic_server_certificate_directory }}/private/{{ restic_server_certificate_name }}.key.pem"
restic_server_certificate_private_key_size: 4096

restic_server_certificate_signing_request_file: "{{ restic_server_certificate_directory }}/csr/{{ restic_server_certificate_name }}.csr.pem"
restic_server_certificate_signing_request_config_file: "{{ restic_server_certificate_directory }}/cnf/{{ restic_server_certificate_name }}.csr.cnf"

restic_server_certificate_authority: false

restic_server_certificate_key_usage:
  - digitalSignature
  - keyEncipherment
restic_server_certificate_extended_key_usage:
  - serverAuth
restic_server_certificates_basic_constraints:
  - "CA: TRUE"
  - "pathlen: 256"
