# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
galaxy_info:
  author: Mirian Brechtel
  description: Git-based pull deployment strategy
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
  galaxy_tags:
    - deployment

dependencies: []
