# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Install bash
  ansible.builtin.apt:
    name: bash
    state: present

- name: Bash powerline-go prompt
  ansible.builtin.copy:
    src: powerline-go.sh
    dest: /etc/profile.d/powerline-go.sh
    mode: "0644"
