---
# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

storage_packages:
  # hard disk utils
  - parted
  - mdadm
  - cryptsetup
  - lvm2

  # filesystem tools
  - btrfs-progs
  - dosfstools
