# SPDX-FileCopyrightText: 2024 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2024 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
# SPDX-FileCopyrightText: 2025 Vasilii Tulskii <tulskyva@mail.ru>
#
# SPDX-License-Identifier: Apache-2.0 OR EUPL-1.2

---

- name: Enable modules
  apache2_module:
    name: "{{item}}"
    state: present
  with_items:
    - rewrite
    - ssl
  notify: restart apache
