# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Configure resolvconf
  when: resolvconf_enabled
  block:
    - name: Resolvconf debian package
      ansible.builtin.apt:
        pkg: resolvconf

    - name: Link resolv.conf
      ansible.builtin.file:
        src: /run/resolvconf/resolv.conf
        dest: /etc/resolv.conf
        state: link
        force: true
