version = 1
SPDX-PackageName = "osahris.cute_devops"
SPDX-PackageSupplier = "Mirian Brechtel <markus.katharina.brechtel@thengo.net>"
SPDX-PackageDownloadLocation = "https://github.com/osahris/cute-devops"
