version = 1
SPDX-PackageName = "mkbrechtel.devops"
SPDX-PackageSupplier = "Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>"
SPDX-PackageDownloadLocation = "https://github.com/mkbrechtel/devops"
