---

- name: create directory for virtual domain {{ virtual_domain }}
  file:
    path: "/opt/rps-admin-tools/{{ virtual_domain }}"
    state: directory

- name: create directory for virtual domain {{ virtual_domain }}
  file:
    path: "/opt/rps-admin-tools/{{ virtual_domain }}/rps_sync_services"
    state: directory

- name: create directory for virtual domain {{ virtual_domain }}
  file:
    path: "/opt/rps-admin-tools/{{ virtual_domain }}/rps_sync_services/mail-templates"
    state: directory

# - name: copy family.xml.j2 to directory
#   file:
#     src: family.xml.j2
#     state: file
#     dest: "/opt/rps-admin-tools/{{ virtual_domain }}/rps_sync_services/mail-templates/family.xml"

- name: "copy family.xml.j2 to /opt/rps-admin-tools/{{ virtual_domain }}/rps_sync_services/mail-templates/family.xml.j2"
  copy:
    src: templates/family.xml.j2
    dest: "/opt/rps-admin-tools/{{ virtual_domain }}/rps_sync_services/mail-templates/family.xml.j2"

- name: copy test.env.j2 to directory
  template:
    src: test.env.j2
    dest: "/opt/rps-admin-tools/{{ virtual_domain }}/test.env"
    
