---

- name: dovecot sql config
  template:
    src: dovecot-sql.conf.ext.j2
    dest: /etc/dovecot/dovecot-sql.conf.ext.j2
  notify:
    - reload dovecot

- name: postfixadmin mysql user
  mysql_user:
    name: "{{dovecot_postfixadmin_mysql_username}}"
    password: "{{dovecot_postfixadmin_mysql_password}}"
    priv: "{{dovecot_postfixadmin_mysql_database}}.*:SELECT"
    host: "{{inventory_hostname}}"
    state: present
  delegate_to: "{{dovecot_postfixadmin_mysql_host}}"
