# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
motd_content: |
  This system is managed by the osahris.cute_devops Ansible collection.
  Manual changes may be overwritten without warning!
