# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
motd_content: |
  This system is managed by the mkbrechtel.devops Ansible collection.
  Manual changes may be overwritten without warning!
