---

- name: install package
  apt:
    pkg: "{{ item }}"
  with_items:
    - dovecot-imapd
    - dovecot-lmtpd

- name: dovecot main configuration file
  template:
    src: dovecot.conf.j2
    dest: /etc/dovecot/dovecot.conf

- name: dovecot configuration files
  template:
    src: conf.d/{{ item }}.j2
    dest: /etc/dovecot/conf.d/{{ item }}
  with_items:
    - 10-mail.conf

- name: configuration pull directory
  local_action: file
  args:
    path: host_files/{{inventory_hostname}}/etc
    state: directory

- name: pull configuration
  synchronize:
    src: /etc/dovecot
    dest: host_files/{{inventory_hostname}}/etc/
    mode: pull
    recursive: true
