---

- name: install apt packages
  apt:
    pkg: "{{item}}"
    state: present
  with_items:
    - apache2
    - libapache2-mod-php
    - composer
    - php-zip
    - php-mbstring
    - php-xml

- name: remove default page
  file:
    path: /var/www/html/index.html
    state: absent
