---

- name: debian packages
  apt:
    pkg:
      - apache2

- name: remove default page
  file:
    path: /var/www/html/index.html
    state: absent

- name: make sure default directory exists
  file:
    path: /var/www/default/
    state: directory
