---
- name: Install list aliases file
  copy:
    src: files/list_aliases.tt2
    dest: "{{ sympa_config_directory }}/list_aliases.tt2"
    owner: sympa
    group: sympa
    mode: 0644

- name: Creating Sympa aliases file (1/2)
  file:
    path: "{{ sympa_mail_alias_file }}"
    state: touch
    owner: sympa
    group: sympa
    mode: 0644

- name: Creating Sympa aliases file (2/2)
  file:
    path: "{{ sympa_mail_alias_file }}.db"
    state: touch
    owner: sympa
    group: sympa
    mode: 0644

- name: Compiling sympa_aliases
  command: "postmap {{ sympa_mail_alias_file }}"

- name: Adding list domains as virtual domains
  copy:
    dest: /etc/postfix/domains.sympa
    content: "{{ sympa_domains | join(\"\n\") }}"

- name: Compiling Sympa domains
  command: postmap /etc/postfix/domains.sympa

- name: Adding required generic aliases
  copy:
    dest: /etc/postfix/virtual.sympa
    content: |-
      {% for domain in sympa_domains %}
      # {{domain}}
      sympa-request@{{ domain }}  listmaster@localhost
      sympa-owner@{{ domain }}    listmaster@localhost
      {% endfor %}

- name: Compiling Sympa transport
  command: postmap /etc/postfix/virtual.sympa

- name: Adding required generic transports
  copy:
    dest: /etc/postfix/transport.sympa
    content: |-
      {% for domain in sympa_domains %}
      # {{domain}}
      sympa@{{ domain }}          sympa:sympa@{{ domain }}
      listmaster@{{ domain }}     sympa:listmaster@{{ domain }}
      bounce@{{ domain }}         sympabounce:sympa@{{ domain }}
      abuse-feedback-report@{{ domain }}  sympabounce:sympa@{{ domain }}
      {% endfor %}

- name: Compiling Sympa transport
  command: postmap /etc/postfix/transport.sympa
