# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
galaxy_info:
  author: mkbrechtel
  description: Network connectivity monitoring using Nagios check_ping plugin
  company: mkbrechtel
  license: EUPL-1.2
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - monitoring
    - network
    - ping

dependencies: []
