---

- name: restart apache2
  command: systemctl restart apache2

- include_role:
    name: certificate
  vars:
    certificate_name: "{{mailname}}"
    certificate_common_name: "{{mailname}}"
    certificate_directory: /etc/ssl
    certificate_key_usage:
      - digitalSignature
      - keyEncipherment
    certificate_extended_key_usage:
      - serverAuth
