# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Install monitoring-plugins-basic packages
  ansible.builtin.apt:
    pkg:
      - monitoring-plugins-basic

- name: Create base directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: u=rwX,g=rX,o=rX
    owner: root
    group: root
  loop:
    - /etc/checker
    - /etc/checker/checks
    - /etc/checker/notifiers
    - /run/checker

- name: Copy readme files
  ansible.builtin.copy:
    src: dir-readme/
    dest: /etc/checker/
    mode: u=rwX,g=rX,o=rX
    owner: root
    group: root

- name: Copy scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/checker/{{ item }}"
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root
  loop:
    - checker.sh
    - notify.sh

- name: Install checker monitor script
  ansible.builtin.copy:
    src: checker-monitor.sh
    dest: /usr/local/bin/checker-monitor
    mode: "0755"
    owner: root
    group: root

- name: Copy Ansible templates
  ansible.builtin.copy:
    src: systemd/
    dest: /etc/systemd/system/
    mode: u=rwX,g=rX,o=rX
    owner: root
    group: root
  notify:
    - Reload systemd daemon
