# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
galaxy_info:
  author: mkbrechtel
  description: Sets up restic REST server for backup storage with authentication
  company: mkbrechtel
  license: AGPL-3.0-or-later
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - trixie
  galaxy_tags:
    - backup
    - restic
    - server

dependencies: []
