---
# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

debian_apt_sources_distribution: trixie
debian_apt_sources_mirror: http://deb.debian.org/debian

debian_apt_sources_with_contrib_component: false
debian_apt_sources_with_non_free_firmware_component: true
debian_apt_sources_with_non_free_component: false

debian_apt_sources_with_updates_suite: true
debian_apt_sources_with_backports_suite: false

debian_apt_sources_with_security_suite: true
debian_apt_sources_security_mirror: https://security.debian.org/debian-security

debian_apt_sources_with_source_packages: true
debian_apt_sources_with_security_source_packages: "{{ debian_apt_sources_with_source_packages }}"
