# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Set MOTD
  ansible.builtin.copy:
    content: "{{ motd_content }}"
    dest: /etc/motd
    owner: root
    group: root
    mode: "0644"
  when: motd is defined
