# SPDX-FileCopyrightText: 2026 Alexander Hirsch <Hirsch@med.uni-frankfurt.de>
# SPDX-FileCopyrightText: 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Add passwordless sudo group
  ansible.builtin.include_tasks: add.yaml
  when: passwordless_sudo_group_enable

- name: Remove passwordless sudo group
  ansible.builtin.include_tasks: remove.yaml
  when: not passwordless_sudo_group_enable
