# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---

- name: Zonefiles directory
  ansible.builtin.file:
    path: "{{ knot_nameserver_zonefile_directory }}"
    state: directory
    mode: "0755"

- name: Copy zonefiles
  ansible.builtin.copy:
    src: zonefiles/{{ zone.domain }}.zone
    dest: "{{ knot_nameserver_zonefile_directory }}/{{ zone.domain }}.zone"
    mode: "0644"
  notify: "Reload knot"
  loop: "{{ nameserver_zones }}"
  loop_control:
    loop_var: zone
    label: "{{ zone.domain }}"
