# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
notify_alerta_api_alert_url: http://localhost:8080/api/alert
notify_alerta_api_key: "EUeDlg7Ro4tKlOMW5-v5nMnTa08F1atbRIvavs3-"
notify_alerta_environment: Development
