# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---

deploy_ansible_pull_common_option_args: >-
  {% if deploy_ansible_pull_accept_host_key %}
  --accept-host-key
  {% endif %}

  {% if deploy_ansible_pull_become_password_file %}
  --become-password-file {{ deploy_ansible_pull_become_password_file | quote }}
  {% endif %}

  {% if deploy_ansible_pull_check %}
  --check
  {% endif %}

  {% if deploy_ansible_pull_clean %}
  --clean
  {% endif %}

  {% if deploy_ansible_pull_connection_password_file %}
  --connection-password-file {{ deploy_ansible_pull_connection_password_file | quote }}
  {% endif %}

  {% if deploy_ansible_pull_diff %}
  --diff
  {% endif %}

  {% if deploy_ansible_pull_full %}
  --full
  {% endif %}

  {% if deploy_ansible_pull_private_key_file %}
  --private-key {{ deploy_ansible_pull_private_key_file | quote }}
  {% endif %}

  {% if deploy_ansible_pull_purge %}
  --purge
  {% endif %}

  {% if deploy_ansible_pull_scp_extra_args %}
  --scp-extra-args {{ deploy_ansible_pull_scp_extra_args | quote }}
  {% endif %}

  {% if deploy_ansible_pull_sftp_extra_args %}
  --sftp-extra-args {{ deploy_ansible_pull_sftp_extra_args | quote }}
  {% endif %}

  {% if deploy_ansible_pull_skip_tags %}
  --skip-tags {{ deploy_ansible_pull_skip_tags | quote }}
  {% endif %}

  {% if deploy_ansible_pull_ssh_common_args %}
  --ssh-common-args {{ deploy_ansible_pull_ssh_common_args | quote }}
  {% endif %}

  {% if deploy_ansible_pull_ssh_extra_args %}
  --ssh-extra-args {{ deploy_ansible_pull_ssh_extra_args | quote }}
  {% endif %}

  {% if deploy_ansible_pull_track_subs %}
  --track-subs
  {% endif %}

  {% if deploy_ansible_pull_vault_id %}
  --vault-id {{ deploy_ansible_pull_vault_id | quote }}
  {% endif %}

  {% if deploy_ansible_pull_vault_password_file %}
  --vault-password-file {{ deploy_ansible_pull_vault_password_file | quote }}
  {% endif %}

  {% if deploy_ansible_pull_verify_commit %}
  --verify-commit
  {% endif %}

  {% if deploy_ansible_pull_checkout %}
  --checkout {{ deploy_ansible_pull_checkout | quote }}
  {% endif %}

  {% if deploy_ansible_pull_module_path %}
  --module-path {{ deploy_ansible_pull_module_path | quote }}
  {% endif %}

  {% if deploy_ansible_pull_timeout %}
   --timeout {{ deploy_ansible_pull_timeout | quote }}
  {% endif %}

  {% if deploy_ansible_pull_url %}
  --url {{ deploy_ansible_pull_url | quote }}
  {% endif %}

  {% if deploy_ansible_pull_connection %}
  --connection {{ deploy_ansible_pull_connection | quote }}
  {% endif %}

  {% if deploy_ansible_pull_directory %}
  --directory $(realpath {{ deploy_ansible_pull_directory | quote }})
  {% endif %}

  {% if deploy_ansible_pull_extra_vars %}
  --extra-vars {{ deploy_ansible_pull_extra_vars | quote }}
  {% endif %}

  {% if deploy_ansible_pull_force %}
  --force
  {% endif %}

  {% if deploy_ansible_pull_inventory %}
  --inventory {{ deploy_ansible_pull_inventory | quote }}
  {% endif %}

  {% if deploy_ansible_pull_limit %}
  --limit {{ deploy_ansible_pull_limit | quote }}
  {% endif %}

  {% if deploy_ansible_pull_module_name %}
  --module-name {{ deploy_ansible_pull_module_name | quote }}
  {% endif %}

  {% if deploy_ansible_pull_only_if_changed %}
  --only-if-changed
  {% endif %}

  {% if deploy_ansible_pull_sleep %}
  --sleep {{ deploy_ansible_pull_sleep | quote }}
  {% endif %}

  {% if deploy_ansible_pull_tags %}
  --tags {{ deploy_ansible_pull_tags | quote }}
  {% endif %}

  {% if deploy_ansible_pull_remote_user %}
  --user {{ deploy_ansible_pull_remote_user | quote }}
  {% endif %}

  {% if deploy_ansible_pull_verbose %}
  --verbose
  {% endif %}

deploy_ansible_pull_playbooks_args: >-
  {% if deploy_ansible_pull_playbooks is iterable %}
  {% for playbook in deploy_ansible_pull_playbooks %}
  {{ playbook }}
  {% endfor %}
  {% else %}
  {{ deploy_ansible_pull_playbooks }}
  {% endif %}
