# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Include deploy instance role
  ansible.builtin.include_role:
    role: deploy
  vars:
    deploy_id: "{{ test_deploy_fail_instance_id }}"

- name: Template init script for deploy instance {{ test_deploy_fail_instance_id }}
  ansible.builtin.template:
    src: 01-test-fail-init.j2
    dest: "/etc/deploy/{{ test_deploy_fail_instance_id }}/01-test-fail-init"
    mode: "0755"

- name: Template deploy script for deploy instance {{ test_deploy_fail_instance_id }}
  ansible.builtin.template:
    src: 02-test-fail.j2
    dest: "/etc/deploy/{{ test_deploy_fail_instance_id }}/02-test-fail"
    mode: "0755"
