# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Upgrade all packages
  ansible.builtin.apt:
    upgrade: dist

- name: Unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
  when:
    - updates_unattended_upgrades
    - not ansible_bender is defined

- name: Reboot after updates
  ansible.builtin.reboot:
  when: updates_reboot_after_updates
