---

- name: set keycloak client config
  local_action: keycloak_client
  become: false
  args:
    auth_client_id: "{{ sympa_sync_keycloak_client_auth_client_id }}"
    auth_keycloak_url: "{{ sympa_mailinglist_envs[virtual_domain].keycloak_url }}"
    auth_realm: "master"
    auth_username: "{{ sympa_mailinglist_envs[virtual_domain].keycloak_auth_username }}"
    auth_password: "{{ sympa_mailinglist_envs[virtual_domain].keycloak_auth_password }}"
    client_id: "{{ sympa_mailinglist_envs[virtual_domain].keycloak_client_id }}"
    realm: "{{ sympa_mailinglist_envs[virtual_domain].keycloak_realm }}"
    client_authenticator_type: client-secret
    secret: "{{ sympa_sync_keycloak_client_secret }}"
    state: present
    publicClient: false
    direct_access_grants_enabled: true
    service_accounts_enabled: true
    validate_certs: "{{ sympa_sync_keycloak_client_validate_certs | default(true) }}"
    # backchannel logout url: https://my.permission_sync.org/apps/user_oidc/backchannel-logout/{{client_id}}
    protocol_mappers:
      - name: groups
        config:
          access.token.claim: 'false'
          claim.name: groups
          full.path: 'false'
          id.token.claim: 'false'
          userinfo.token.claim: 'true'
        consentRequired: false
        protocol: openid-connect
        protocolMapper: oidc-group-membership-mapper

- name: "Create access_token for keycloak for user {{ sympa_sync_keycloak_client_auth_username }}"
  local_action: uri
  become: false
  args:
    url: "{{ sympa_mailinglist_envs[virtual_domain].keycloak_url }}/realms/master/protocol/openid-connect/token"
    method: POST
    validate_certs: true
    body_format: form-urlencoded
    body:
      username: "{{ sympa_mailinglist_envs[virtual_domain].keycloak_auth_username }}"
      password: "{{ sympa_mailinglist_envs[virtual_domain].keycloak_auth_password | mandatory }}"
      grant_type: "password"
      client_id: "admin-cli"
  register: keycloak_token

- name: Map a client role to a service account user for a client, authentication with credentials
  community.general.keycloak_user_rolemapping:
    realm: "{{ sympa_mailinglist_envs[virtual_domain].keycloak_realm }}"
    auth_keycloak_url: "{{ sympa_mailinglist_envs[virtual_domain].keycloak_url }}"
    token: "{{ keycloak_token.json.access_token }}"
    state: present
    client_id: realm-management
    service_account_user_client_id : "{{ sympa_mailinglist_envs[virtual_domain].keycloak_client_id }}"
    roles:
      - name: view-users
      - name: query-users
      # - name: manage-users
      - name: view-realm
      - name: query-realms

- name: Map a client role to a service account user for a client, authentication with credentials
  community.general.keycloak_user_rolemapping:
    realm: "{{ sympa_mailinglist_envs[virtual_domain].keycloak_realm }}"
    auth_keycloak_url: "{{ sympa_mailinglist_envs[virtual_domain].keycloak_url }}"
    token: "{{ keycloak_token.json.access_token }}"
    state: present
    client_id: account
    service_account_user_client_id : "{{ sympa_mailinglist_envs[virtual_domain].keycloak_client_id }}"
    roles:
      - name: view-groups