---
- name: Ensure ansible facts directory exists
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: Copy keycloak secrets facts
  copy:
    content: "{{ sympa_sync_secrets | to_nice_json }}\n"
    dest: /etc/ansible/facts.d/{{sympa_main_domain}}.fact
  register: sympa_sync_secrets_facts_copy_task

- name: Gather facts again after secrets generation
  setup:
  when: sympa_sync_secrets_facts_copy_task.changed
