# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
galaxy_info:
  author: mkbrechtel
  description: SSH and GPG agent systemd user service setup
  company: mkbrechtel
  license: EUPL-1.2
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - trixie
  galaxy_tags:
    - ssh
    - gpg
    - systemd

dependencies: []
