# SPDX-FileCopyrightText: 2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
repos_default_group: devops
repos_default_owner: root
repos_default_branch: main
repos_with_treehouses: true
repos_with_claude_hooks: true
repos_with_deploy: false
repos_with_safe_directory: true
repos_safe_directory: /srv/repos/*
