# SPDX-FileCopyrightText: 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
repos_default_group: devops
repos_default_owner: root
repos_with_treehouses: true
repos_with_claude_hooks: true
