# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure /etc/deploy directory exists
  ansible.builtin.file:
    path: /etc/deploy
    state: directory
    mode: "0755"
  become: true

- name: Install notification scripts
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/deploy/{{ item | basename }}"
    mode: "0755"
  loop:
    - notify.sh
    - notify-email.sh
  become: true

- name: Install system units
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename }}"
    mode: "0644"
  with_fileglob:
    - "systemd/system/*"
  loop_control:
    label: "{{ item | basename }}"
  become: true
  notify: Reload systemd daemon

- name: Flush all handlers after unit file copying is finished
  ansible.builtin.meta: flush_handlers
