# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Make ssh-agent user service override directory
  ansible.builtin.file:
    path: /etc/systemd/user/ssh-agent.service.d
    state: directory
    mode: "0755"

- name: Make ssh-agent user service enableable
  ansible.builtin.copy:
    src: ssh-agent.service.d.install
    dest: /etc/systemd/user/ssh-agent.service.d/install.conf
    mode: "0644"

- name: Ensure ssh-agent user service is enabled for all users
  ansible.builtin.systemd:
    enabled: true
    scope: global
    name: ssh-agent.service

- name: Ensure gpg-agent user socket is enabled for all users
  ansible.builtin.systemd:
    enabled: true
    scope: global
    name: gpg-agent.socket

- name: Pam_env.conf
  ansible.builtin.copy:
    src: pam_env.conf
    dest: /etc/security/pam_env.conf
    mode: "0644"
