# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

# Notification settings
deploy_deploy_notify_email_to: ""
deploy_deploy_notify_email_from: "deploy@{{ ansible_hostname }}"
deploy_deploy_notify_email_on_success: false
deploy_deploy_notify_email_on_failure: true
deploy_deploy_notify_email_max_output_lines: 100
deploy_deploy_notify_email_rate_limit: 10
