---
- name: update apt cache
  apt:
    update_cache: yes

- name: install packages
  apt:
    pkg:
      - postfix
      #- libsasl2-modules-postfix
      - rsyslog
      - mailutils

- name: master configuration
  template:
    src: master.cf.j2
    dest: /etc/postfix/master.cf
  notify: restart postfix

- name: main configuration
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
  notify: reload postfix

- name: postfix transport_maps
  template:
    src: transport_maps.j2
    dest: /etc/postfix/transport_maps
  notify: postmap transport_maps

- name: postfix virtual_alias_domains
  template:
    src: virtual_alias_domains.j2
    dest: /etc/postfix/virtual_alias_domains
  notify: postmap virtual_alias_domains

- name: postfix virtual_alias_maps
  template:
    src: virtual_alias_maps.j2
    dest: /etc/postfix/virtual_alias_maps
  notify: postmap virtual_alias_maps

- name: postfix virtual_mailbox_domains
  template:
    src: virtual_mailbox_domains.j2
    dest: /etc/postfix/virtual_mailbox_domains
  notify: postmap virtual_mailbox_domains

- name: postfix virtual_mailbox_maps
  template:
    src: virtual_mailbox_maps.j2
    dest: /etc/postfix/virtual_mailbox_maps
  notify: postmap virtual_mailbox_maps

- import_tasks: spf.yaml
  when: postfix_with_spf_check

- import_tasks: opendkim.yaml
  when: postfix_with_opendkim

- import_tasks: opendmarc.yaml
  when: postfix_with_opendmarc

- import_tasks: postfixadmin.yml
  when: postfix_with_postfixadmin

- name: check postfix configuration
  command: postfix check
  changed_when: false

- name: postmap transport_maps
  command: postmap /etc/postfix/transport_maps

- name: postmap virtual_alias_domains
  command: postmap /etc/postfix/virtual_alias_domains

- name: postmap virtual_alias_maps
  command: postmap /etc/postfix/virtual_alias_maps

- name: postmap virtual_mailbox_domains
  command: postmap /etc/postfix/virtual_mailbox_domains

- name: postmap virtual_mailbox_maps
  command: postmap /etc/postfix/virtual_mailbox_maps
  notify: restart postfix

# - name: chown root:postfix transport_maps
#   command: chown root:postfix /etc/postfix/transport_maps.db

- import_tasks: certbot.yaml
  when: postfix_with_ssl

# - import_tasks: configure-ssl.yaml
#   when: postfix_with_ssl

# repair permissions for opendkim and opendmarc
- name: repair permissions for opendkim
  command: chown -R opendkim:opendkim /var/run/opendkim
  when: postfix_with_opendkim

- name: repair permissions for opendmarc
  command: chown -R opendmarc:opendmarc /var/run/opendmarc
  when: postfix_with_opendmarc

- name: restart postfix opendkim opendmarc
  command: systemctl restart postfix opendkim opendmarc
  notify: restart postfix
