---
sympa_secrets:
  sympa_postgres_password: "{{ sympa_postgres_password | default(lookup('ansible.builtin.password', '/dev/null length=32 chars=ascii_letters,digits')) }}"

sympa_debconf:
  - question: sympa/database-type
    value: pgsql
    vtype: select
  - question: sympa/pgsql/app-pass
    value: "{{ sympa_postgres_password }}"
    vtype: select
