# SPDX-FileCopyrightText: 2023-2024 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2023-2024 Uniklinik Köln
#
# SPDX-License-Identifier: Apache-2.0 OR EUPL-1.2

postfix_smtpd_sasl_type: dovecot
postfix_smtpd_sasl_path: private/auth
postfix_smtpd_sasl_auth_enable: true
