---
# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

ansible_installed_version: "{% if get_ansible_version.stdout != '' %}{{ get_ansible_version.stdout }}{% else %}0{% endif %}"
