---

- name: directory
  file:
    path: "{{ certificate_directory }}"
    state: directory

- name: subdirectories
  file:
    path: "{{ certificate_directory }}/{{item}}"
    state: directory
  with_items:
    - certs
    - csr
    - cnf
    - private

- name: private directory
  file:
    path: "{{ certificate_directory }}/private"
    # TODO: these are the debian default perms; check if they are generically applicable for us
    owner: root
    #group: ssl-cert
    mode: 0710

