# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Install fish
  ansible.builtin.apt:
    name: fish
    state: present

- name: Fish config directory
  ansible.builtin.file:
    path: /etc/fish/conf.d
    state: directory
    mode: "0755"

- name: Fish config files
  ansible.builtin.copy:
    src: global/
    dest: /etc/fish/conf.d/
    mode: "0644"
  with_items:
    - fish_title
    - fish_prompt
    - fish_greeting
