---

# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

debian_apt_sources_components: >-
  main
  {% if debian_apt_sources_with_contrib_component %}contrib{% endif %}
  {% if debian_apt_sources_with_non_free_firmware_component %}non-free-firmware{% endif %}
  {% if debian_apt_sources_with_non_free_component %}non-free{% endif %}

debian_apt_sources_types: >-
  deb
  {% if debian_apt_sources_with_source_packages %}deb-src{% endif %}

debian_apt_sources_security_types: >-
  deb
  {% if debian_apt_sources_with_security_source_packages %}deb-src{% endif %}

debian_apt_sources_suites: >-
  {{ debian_apt_sources_distribution }}
  {% if debian_apt_sources_with_updates_suite %}{{ debian_apt_sources_distribution }}-updates{% endif %}
  {% if debian_apt_sources_with_backports_suite %}{{ debian_apt_sources_distribution }}-backports{% endif %}

debian_apt_sources_security_suites: >-
  {{ debian_apt_sources_distribution }}-security
