# SPDX-FileCopyrightText: 2013 - 2022 Philipp Kaluza <consult@ghostroute.eu>
# SPDX-FileCopyrightText: 2016 - 2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
# - import_tasks: local_facts.yaml

- name: Ensure restic is installed from distribution repositories
  ansible.builtin.apt:
    name:
      - restic
      - pwgen
      - apache2-utils
    state: present

- name: Create /etc/restic directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/restic
    - /etc/restic/config

- name: Create /etc/restic directories (II)
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - /etc/restic/repositories
    - /etc/restic/passwords

- name: Create directory for ansible custom facts
  ansible.builtin.file:
    state: directory
    mode: "0700"
    path: /etc/ansible/facts.d

- name: Write out restic per-repos secrets
  ansible.builtin.copy:
    dest: "/etc/restic/repositories/{{ item.repository }}.key"
    content: "{{ item.key }}"
    mode: "0600"
  loop: "{{ restic_client_backup_directives }}"

- name: Generate per-server credentials
  ansible.builtin.shell:
    creates: "/etc/restic/passwords/{{ restic_client_backup_url_hostport | b64encode }}.pw"
    cmd: "set -o pipefail && /usr/bin/pwgen -s 16 | dd bs=1 count=16 > /etc/restic/passwords/{{ restic_client_backup_url_hostport | b64encode }}.pw"
  args:
    executable: /bin/bash
  # TODO: loop over multiple servers, once possible

- name: Hash per-server credentials
  ansible.builtin.shell:
    # always regenerate the facts file until we have a [TODO] trigger for regenerating the password
    cmd: >-
      set -o pipefail &&
      ( /bin/echo -en "[backupuser_htpasswds]\npw1=" ;
      /usr/bin/cat /etc/restic/passwords/{{ restic_client_backup_url_hostport | b64encode }}.pw
      | /usr/bin/htpasswd -niB {{ ansible_hostname | quote }} )
      > /etc/ansible/facts.d/backupuser_htpasswds.fact
      && chmod 600 /etc/ansible/facts.d/backupuser_htpasswds.fact
    executable: /bin/bash
  changed_when: true

- name: Re-read facts after adding custom fact
  ansible.builtin.setup:
    filter: ansible_local

- name: Loop over servers to re-generate .htpasswd files there
  loop: "{{ groups['backup_servers'] }}"
  loop_control:
    loop_var: backupserver
  # To combine loop/include_tasks with delegate, we include an intermediate task file
  ansible.builtin.include_tasks: perserver.yaml
- name: Create the restic per-backup config files
  ansible.builtin.template:
    src: "per_backup.env.j2"
    dest: "/etc/restic/config/{{ item.name }}.env.tmpl"
    mode: "0600"
  loop: "{{ restic_client_backup_directives }}"
  when: item.content is undefined
  # The Systemd service unit will read these via EnvironmentFile=

- name: Create the restic per-backup config files (for special cases)
  ansible.builtin.copy:
    dest: "/etc/restic/config/{{ item.name }}.env.tmpl"
    content: "{{ item.content }}"
    mode: "0600"
  loop: "{{ restic_client_backup_directives }}"
  when: item.content is defined
  # or these, depending on the configuration

- name: Finalize the restic per-backup config files client-side
  ansible.builtin.shell:
    cmd: >
      umask 0177 ;
      /usr/bin/sed -e "s/%INSERT_PASSWORD_HERE%/$(/usr/bin/cat
      /etc/restic/passwords/{{ restic_client_backup_url_hostport | b64encode }}.pw)/"
      < /etc/restic/config/{{ item.name | quote }}.env.tmpl
      > /etc/restic/config/{{ item.name | quote }}.env
      && chmod 0600 /etc/restic/config/{{ item.name | quote }}.env
  changed_when: true
  loop: "{{ restic_client_backup_directives }}"

# - name: Check repository initialization and status
#   ansible.builtin.shell:
#     creates: "/etc/restic/repositories/{{ item.repository|quote }}.initialized"
#     cmd: >
#       restic stats --json -r {{ restic_client_backup_url | quote }}{{ item.repository | quote }}
#         --password-file "/etc/restic/repositories/{{ item.repository | quote }}.key"
#           > /etc/ansible/facts.d/restic-repos-{{ item.repository | quote }}.fact   &&
#       touch '/etc/restic/repositories/{{ item.repository|quote }}.initialized'
#   failed_when: false
#   loop: "{{ restic_client_backup_directives }}"
#   register: repository_x_stats

- name: Create a file with the servers' certs
  ansible.builtin.template:
    src: "restic-server-certs.pem.j2"
    dest: "/etc/ssl/certs/restic-server-certs.pem"
    mode: "0644"

- name: Create repository where necessary
  ansible.builtin.shell:
    creates: "/etc/restic/repositories/{{ item.repository | quote }}.initialized"
    cmd: >
      . /etc/restic/config/{{ item.name | quote }}.env ;
      export RESTIC_REPOSITORY RESTIC_PASSWORD_FILE GODEBUG ;
      restic init --json $RESTIC_FLAGS_CACERT &&
      touch '/etc/restic/repositories/{{ item.repository | quote }}.initialized'
  loop: "{{ restic_client_backup_directives }}"

- name: Deploy service unit for restic client
  ansible.builtin.template:
    src: "restic-backup-oneshot@.service"
    dest: "/etc/systemd/system/"
    mode: "0644"

- name: Deploy specialized service unit for database backups
  ansible.builtin.template:
    src: "restic-backup-oneshot@database.service.j2"
    dest: "/etc/systemd/system/restic-backup-oneshot@{{ item.name | quote }}.service"
    mode: "0644"
  loop: "{{ restic_client_backup_directives }}"
  when: item.database_dump_command is defined

- name: Remove specialized service unit where unnecessary
  ansible.builtin.file:
    path: "/etc/systemd/system/restic-backup-oneshot@{{ item.name | quote }}.service"
    state: absent
  loop: "{{ restic_client_backup_directives }}"
  when: item.database_dump_command is undefined

- name: Deploy timer units for restic client
  ansible.builtin.template:
    src: "restic-backup-daily@.timer"
    dest: "/etc/systemd/system/"
    mode: "0644"

- name: Have SystemD re-read configs
  ansible.builtin.systemd:
    daemon_reload: true

- name: Have SystemD enable the timer units
  ansible.builtin.systemd:
    name: "restic-backup-daily@{{ item.name | quote }}.timer"
    enabled: true
  loop: "{{ restic_client_backup_directives }}"
