# SPDX-FileCopyrightText: 2013 - 2022 Philipp Kaluza <consult@ghostroute.eu>
# SPDX-FileCopyrightText: 2016 - 2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Import restic_server htpasswd tasks on backup server
  ansible.builtin.import_role:
    name: restic_server
    tasks_from: htpasswd
  delegate_to: "{{ backupserver }}"
  delegate_facts: true
