---

- name: Install Sympa configuration file
  template:
    src: sympa.conf.j2
    dest: /etc/sympa/sympa/sympa.conf
    owner: sympa
    group: sympa
    mode: 0640
  tags: sympa.conf
  notify: restart sympa
