---

- name: Generate Sympa secrets
  tags: sympa-secrets
  import_tasks: secrets.yaml

- name: Setup Sympa
  tags: sympa-setup
  import_tasks: setup.yaml

# - name: Install and configure database
#   tags: sympa-db
#   import_tasks: db.yaml

- name: Sympa post-install operations
  tags: sympa-config
  import_tasks: config.yaml

# - name: Configure postfix and mail aliases
#   tags: sympa-mail
#   import_tasks: mail.yaml

- name: Configure Apache
  tags: sympa-web
  import_tasks: web.yaml
  # TODO: add certificate generation
  # TODO: add apache vhost configuration

- name: loop over sympa_domains to create virtual robots
  tags: sympa-robots
  include_tasks: configure_virtual_domains.yaml
  loop: "{{ sympa_domains | union([sympa_main_domain]) }}"
  loop_control:
    loop_var: virtual_domain
    index_var: virtual_domain_index

- name: restart postfix
  command: systemctl restart postfix

- name: restart sympa
  command: systemctl restart sympa

- name: restart wwsympa
  command: systemctl restart wwsympa