# SPDX-FileCopyrightText: 2024 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2024 Uniklinik Köln
#
# SPDX-License-Identifier: Apache-2.0 OR EUPL-1.2

---
- name: Ensure ansible facts directory exists
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: Copy sympa secrets facts
  copy:
    content: "{{ sympa_secrets | to_nice_json }}\n"
    dest: /etc/ansible/facts.d/sympa.fact
  register: sympa_secrets_facts_copy_task

- name: Gather facts again after secrets generation
  setup:
  when: sympa_secrets_facts_copy_task.changed
