---
- name: Ensure ansible facts directory exists
  file:
    path: /etc/ansible/facts.d
    state: directory

- name: Copy sympa secrets facts
  copy:
    content: "{{ sympa_secrets | to_nice_json }}\n"
    dest: /etc/ansible/facts.d/sympa.fact
  register: sympa_secrets_facts_copy_task

- name: Gather facts again after secrets generation
  setup:
  when: sympa_secrets_facts_copy_task.changed
