---

- name: Preconfigure sympa database type with debconf
  ansible.builtin.debconf:
    name: sympa
    question: sympa/database-type
    value: pgsql
    vtype: select

- name: Preconfigure sympa database password with debconf
  ansible.builtin.debconf:
    name: sympa
    question: sympa/pgsql/app-pass
    value: "{{ sympa_postgres_password }}"
    vtype: password
  no_log: True

- name: Install sympa debian packages
  apt:
    pkg:
      - sympa

# - name: chown sympa:sympa /etc/aliases.db
#   command: chown sympa:sympa /etc/aliases.db
