# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Check if systemd lingering is enabled
  ansible.builtin.stat:
    path: /var/lib/systemd/linger/{{ item }}
  register: _users_systemd_linger_stat
  loop: "{{ users.keys() | list }}"
  when:
    - users[item].linger is defined

- name: Set systemd lingering
  ansible.builtin.command: loginctl {{ users[item].linger | ternary('enable', 'disable') }}-linger {{ item }}
  changed_when: true
  loop: "{{ users.keys() | list }}"
  when:
    - users[item].linger is defined
    - ( _users_systemd_linger_stat.results | json_query("[?item=='"+item+"'].stat.exists") | first ) != users[item].linger
