# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Include OS-specific setup tasks
  ansible.builtin.include_tasks: setup_{{ ansible_os_family }}.yml
- name: Import user groups tasks
  ansible.builtin.import_tasks: user_groups.yml
  when: user_groups is defined

- name: Import user move tasks
  ansible.builtin.import_tasks: move.yaml
  when: users is defined

- name: Import user creation tasks
  ansible.builtin.import_tasks: users.yml
  when: users is defined

- name: Import home directory tasks
  ansible.builtin.import_tasks: home.yml
  when: users is defined

- name: Import SSH tasks
  ansible.builtin.import_tasks: ssh.yml
  when: users is defined

- name: Import linger tasks
  ansible.builtin.import_tasks: linger.yml
  when: users is defined

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
