# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Move group
  ansible.builtin.command: "groupmod --new-name {{ item }} {{ users[item].old_name }}"
  changed_when: true
  loop: "{{ users.keys() | list }}"
  when: users[item].old_name is defined
  failed_when: false

- name: Move account
  ansible.builtin.command: "usermod --login {{ item }} {{ users[item].old_name }}"
  changed_when: true
  loop: "{{ users.keys() | list }}"
  when: users[item].old_name is defined
  failed_when: false
