# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Ssh key
  ansible.builtin.user:
    name: "{{ item }}"
    generate_ssh_key: true
    ssh_key_type: ed25519
  register: user_ssh_keys_info
  loop: "{{ users.keys() | list }}"

- name: Ssh directory
  ansible.builtin.file:
    path: "{{ users[item].home | default('/home/' + item) }}/.ssh"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0700"
    state: directory
  loop: "{{ users.keys() | list }}"

- name: Ssh authorized keys
  ansible.builtin.template:
    src: ssh_authorized_keys.j2
    dest: "{{ users[item].home | default('/home/' + item) }}/.ssh/authorized_keys"
    owner: "{{ item }}"
    group: "{{ item }}"
    mode: "0600"
  loop: "{{ users.keys() | list }}"
  when: users[item].ssh_authorized_keys is defined
