# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Primary group
  ansible.builtin.group:
    name: "{{ item }}"
    gid: "{{ users[item].gid }}"
  loop: "{{ users.keys() | list }}"
  when: users[item].gid is defined

- name: Account
  ansible.builtin.user:
    name: "{{ item }}"
    group: "{{ (item if 'gid' in users[item] else None) | default(omit) }}"
    groups: "{{ users[item].groups | default([]) | join(',') }}"
    uid: "{{ users[item].uid | default(omit) }}"
    home: "{{ users[item].home | default('/home/' + item) }}"
    shell: "{{ users[item].shell | default(omit) }}"
    create_home: true
    move_home: true
  loop: "{{ users.keys() | list }}"
  notify: Restart systemd-logind.service

- name: Password
  ansible.builtin.user:
    name: "{{ item }}"
    password: "{{ users[item].password }}"
  loop: "{{ users.keys() | list }}"
  when: users[item].password is defined
