# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Groups
  ansible.builtin.group:
    name: "{{ item }}"
    gid: "{{ user_groups[item].gid }}"
  loop: "{{ user_groups.keys() | list }}"
