# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---

deploy_ansible_play_instance_id: "{{ undef() }}"

deploy_ansible_play_collections_path:
  - collections
  - /usr/share/ansible/collections

deploy_ansible_play_install_ansible_galaxy_requirements: true

deploy_ansible_play_init_playbook:
  - name: Initialize ansible play environment
    hosts: localhost
    gather_facts: false
    vars:
      install_ansible_galaxy_requirements: "{{ deploy_ansible_play_install_ansible_galaxy_requirements }}"
    tasks:
      - name: Get ansible git repo
        git:
          repo: "{{ deploy_ansible_play_git_repo }}"
          dest: repo
      - name: Install ansible galaxy requirements
        community.general.ansible_galaxy_install:
          type: both
          requirements_file: repo/requirements.yml
        when: install_ansible_galaxy_requirements

deploy_ansible_play_deploy_playbook:
  - import_playbook: "repo/{{ deploy_ansible_play_import_playbook_filename }}"
