---
# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

- name: Install tools packages
  ansible.builtin.apt:
    pkg: "{{ tools_packages }}"
