# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
---
tools_packages:

  # editors
  - nano
  - micro
  - vim
  - joe

  # shells
  - zsh
  - fish
  - elvish
  - sash

  # shell prompt
  - powerline-go

  # shell tools
  - tmux
  - socat
  - jq
  - jo
  - pv
  - qrencode
  - moreutils

  # terminfo
  - kitty-terminfo

  # network tools
  - openssh-client
  - net-tools
  - iputils-ping
  - whois
  - bind9-dnsutils
  - mtr
  - oping
  - ipcalc
  - ipv6calc

  # admin tools
  - lsof
  - less
  - psmisc

  # apt tools
  - aptitude

  # compression
  - unzip
  - p7zip
  - zip
  - xz-utils

  # file sync tools
  - rsync
  - zsync

  # documentation
  - man-db

  # tools
  - pwgen

  # programming
  - python3
  - python3-pip
  - python3-setuptools
  - python3-apt
  - golang

  # encryption tools
  - openssl
  - gnupg
  - gnupg-agent

  # installation utils
  - debootstrap
  - arch-install-scripts

  # hardware utils
  - pciutils
  - usbutils
  - acpi
  - lshw

  # backup clients
  - borgbackup2
  - restic
  - bup
  - zbackup
