# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Debian packages
  ansible.builtin.apt:
    pkg:
      - ansible
      - ansible-core
      - ansible-lint
      - ansible-mitogen
      - python3-jmespath
      - python3-pymysql
      - python3-dnspython
      - python3-libcloud
      - python3-netaddr

- name: Ansible etc directory
  ansible.builtin.file:
    path: /etc/ansible
    state: directory
    mode: "0755"

- name: Ansible config
  ansible.builtin.template:
    src: ansible.cfg.j2
    dest: /etc/ansible/ansible.cfg
    mode: "0644"
