---
# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

- name: Setup ttyd via download
  ansible.builtin.import_tasks: setup_via_download.yaml
  when: ttyd_setup_method == "download"
