# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---
galaxy_info:
  author: mkbrechtel
  description: Install and configure Podman container runtime with DNS support
  company: mkbrechtel
  license: EUPL-1.2
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - bookworm
        - bullseye
    - name: Ubuntu
      versions:
        - jammy
        - focal
  galaxy_tags:
    - podman
    - containers
    - containerization
    - system

dependencies: []
