---
# SPDX-FileCopyrightText: 2013 - 2022 Philipp Kaluza <consult@ghostroute.eu>
# SPDX-FileCopyrightText: 2016 - 2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- name: Check for static restic-rest users on backupserver
  vars:
    static_htpasswd_name: "{{ (restic_server_backupstorage | default('/srv/backupstorage/')) + '.htpasswd-static' }}"
  ansible.builtin.command:
    cmd: "cat {{ static_htpasswd_name | quote }}"
  register: static_htpasswd_contents
  failed_when: false
  changed_when: false

- name: Set contents of .htpasswd file
  ansible.builtin.template:
    src: "htpasswd.j2"
    dest: "{{ restic_server_backupstorage | default('/srv/backupstorage/') }}/.htpasswd"
    owner: root
    group: restic-service
    mode: "0640"
    follow: false

- name: Have Systemd (re)start the restic-rest daemon
  ansible.builtin.systemd:
    daemon_reload: true
    name: restic-server.service
    state: restarted
