---

rps_mail_sync_admin_tools_version: feature/rps-mail-sync
rps_mail_sync_admin_tools_pip_package: git+https://gitlab.com/idcohorts/rps/rps-admin-tools.git@{{ rps_mail_sync_admin_tools_version }}

sympa_sync_keycloak_client_auth_client_id: admin-cli
sympa_sync_keycloak_client_validate_certs: true

# secrets
sympa_sync_keycloak_client_secret: "{{ ansible_local[sympa_main_domain].sympa_sync_keycloak_client_secret }}"