# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Import deploy instance role
  ansible.builtin.import_role:
    role: deploy

- name: Template deploy script for deploy instance {{ deploy_id }}
  ansible.builtin.template:
    src: 01-ansible-pull.j2
    dest: "{{ deploy_folder_path }}/01-ansible-pull"
    mode: "0755"
