# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---
galaxy_info:
  author: Mirian Brechtel
  description: Assert a mail instance's services are up and mail flows end-to-end
  license: EUPL-1.2
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - testing

dependencies: []
