# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Install monitoring-plugins-systemd package
  ansible.builtin.apt:
    pkg:
      - monitoring-plugins-systemd

- name: Import deploy instance role
  ansible.builtin.import_role:
    role: check
