# SPDX-FileCopyrightText: 2023-2024 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2023-2024 Uniklinik Köln
#
# SPDX-License-Identifier: Apache-2.0 OR EUPL-1.2

---

- name: opendmarc debian packages
  apt:
    pkg: opendmarc

- name: opendmarc config
  template:
    src: opendmarc.conf.j2
    dest: /etc/opendmarc.conf
  notify: restart opendmarc
