---
# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

ttyd_arch_map:
  x86_64: x86_64
  aarch64: aarch64
  armv7l: armhf
  armv6l: arm
  i686: i686
  s390x: s390x

ttyd_install_path: "{{ ttyd_install_dir }}/ttyd.{{ ttyd_arch }}"
