---

- name: "Install Sympa [1/3: configure]"
  command: ./configure --prefix={{ sympa_install_directory }} --with-lockdir=/var/lock --without-initdir --with-unitsdir=/etc/systemd/system --with-spooldir=/var/spool/sympa --with-expldir={{ sympa_lists_path }}
  args:
    chdir: "{{ sympa_install_directory }}/src/{{ source_dir }}"

- name: "Install Sympa [2/3: make]"
  command: make
  args:
    chdir: "{{ sympa_install_directory }}/src/{{ source_dir }}"

- name: "Install Sympa [3/3: make install]"
  command: make install
  args:
    chdir: "{{ sympa_install_directory }}/src/{{ source_dir }}"

- name: Fix ownership
  file:
    path: "{{ sympa_install_directory }}"
    owner: "{{ sympa_unix_user }}"
    group: "{{ sympa_unix_group }}"
    recurse: yes

- name: Fix permissions
  command: "find {{ sympa_install_directory }} -type d -exec chmod 0755 '{}' \\;"

- name: Ensuring lib directory is there
  file:
    path: "{{ sympa_lib_directory }}"
    state: directory
    owner: sympa
    group: sympa
    mode: 0755

- name: Ensuring archives directory is there
  file:
    path: "{{sympa_arc_path}}"
    state: directory
    owner: sympa
    group: sympa
    mode: 0755

- name: Ensuring lists directory is there
  file:
    path: "{{sympa_lists_path}}"
    state: directory
    owner: sympa
    group: sympa
    mode: 0755
