dovecot_certificate_fullchain_file: /etc/ssl/certs/{{mailname}}.cert.pem
dovecot_certificate_private_key_file: /etc/ssl/private/{{mailname}}.key.pem

dovecot_users:
  - username: postmaster@tomrobinr.iodatalabs.dev
    password_hash: $5$mZtTwRWOg1eKJAJV$XEsQj91eUCCJV4HawNVvEC5Ss4NON2LHcP7ZJKGLpP0
  - username: accounts@tomrobinr.iodatalabs.dev
    password_hash: $5$pu766BzsCHNM3w.W$ojvSUAfOhX8yAQ9VYCNlPuhPMHvwgmrdrbhcmyw82Q4
  - username: no-reply@tomrobinr.iodatalabs.dev
    password_hash: $5$pu766BzsCHNM3w.W$ojvSUAfOhX8yAQ9VYCNlPuhPMHvwgmrdrbhcmyw82Q4