# SPDX-FileCopyrightText: 2016-2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
check_ping_cmd: check_ping -H {{ check_ping_hostname }} -w 10,2% -c 20,5%
