# SPDX-FileCopyrightText: 2023-2024 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2023-2024 Uniklinik Köln
#
# SPDX-License-Identifier: Apache-2.0 OR EUPL-1.2

dovecot_postfixadmin_mysql_host: localhost
dovecot_postfixadmin_mysql_database: postfixadmin
dovecot_postfixadmin_mysql_username: dovecot
vmail_uid: 500
vmail_gid: 500
dovecot_lmtp_inet_listener: false
dovecot_unix_listeners_for_postfix: true
dovecot_auth_inet_listener: false
dovecot_auth: sql
dovecot_certificate_fullchain_file: /etc/ssl/certs/ssl-cert-snakeoil.pem
dovecot_certificate_private_key_file: /etc/ssl/private/ssl-cert-snakeoil.key
