# SPDX-FileCopyrightText: 2024 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2024 Uniklinik Köln
#
# SPDX-License-Identifier: Apache-2.0 OR EUPL-1.2

---

- name: Install required Debian packages for PostgreSQL
  apt:
    pkg:
      - postgresql
      - libpq-dev
      - python3-psycopg2 # Required by Ansible
    state: present
