# SPDX-FileCopyrightText: 2013 - 2022 Philipp Kaluza <consult@ghostroute.eu>
# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Gather backup server facts
  hosts: backup_servers
  remote_user: root

- name: Configure backup clients
  hosts: backup_clients
  remote_user: root
  roles:
    - role: restic_client
