# SPDX-FileCopyrightText: 2016 - 2026 Mirian Brechtel <markus.katharina.brechtel@thengo.net>
# SPDX-FileCopyrightText: 2020 - 2025 Uniklinik Köln
# SPDX-FileCopyrightText: 2025 - 2026 Goethe-University Frankfurt – Institute for Digital Medicine and Clinical Data Science
#
# SPDX-License-Identifier: EUPL-1.2

---
- name: Increase maximum inotify user watches
  ansible.posix.sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    sysctl_set: true
  when: sysctl_tweaks_increase_maximum_inotify_user_watches
