---
# SPDX-FileCopyrightText: 2013 - 2022 Philipp Kaluza <consult@ghostroute.eu>
# SPDX-FileCopyrightText: 2016 - 2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- name: "Restart daemon on cert change"
  listen: "certificate changed"
  ansible.builtin.systemd:
    name: restic-server.service
    state: restarted

- name: Make new cert available as fact
  listen: "certificate changed"
  ansible.builtin.shell:
    cmd: >-
      ( echo -n "[restic_server_cert]\ncert=" ;
      sed --null-data -e "s/\\n/\\\\n/g" < {{ restic_server_certificate_file | quote }} ;
      echo "" ) > /etc/ansible/facts.d/restic_server_cert.fact
  changed_when: true
