---
# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Ansible Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    steps:
      - name: Install prerequisites
        env:
          DEBIAN_FRONTEND: noninteractive
        run: >-
          apt-get update && apt-get install -y --no-install-recommends
          git ansible ansible-lint

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run ansible-lint
        run: >-
          ansible-lint
