---
# SPDX-FileCopyrightText: 2016-2026 Markus Katharina Brechtel <markus.katharina.brechtel@thengo.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Release Ansible Collection

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: debian:trixie
    steps:
      - name: Install prerequisites
        env:
          DEBIAN_FRONTEND: noninteractive
        run: >-
          apt-get update && apt-get install -y --no-install-recommends
          git ansible-core

      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Build collection
        run: >-
          ansible-galaxy collection build --output-path ./dist

      - name: Get collection filename
        id: get_filename
        run: |-
          COLLECTION_FILE=$(ls ./dist/*.tar.gz)
          echo "COLLECTION_FILE=$(basename $COLLECTION_FILE)" >> $GITHUB_OUTPUT
          echo "COLLECTION_PATH=$COLLECTION_FILE" >> $GITHUB_OUTPUT

      - name: Publish to Ansible Galaxy
        env:
          ANSIBLE_GALAXY_API_KEY: ${{ secrets.ANSIBLE_GALAXY_API_KEY }}
        run: |-
          ansible-galaxy collection publish \
            --api-key="$ANSIBLE_GALAXY_API_KEY" \
            "${{ steps.get_filename.outputs.COLLECTION_PATH }}"
